---
- name: Create a directory prometheus if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
    - /data/prometheus

- name: Create a directory alertManager if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  with_items:
    - /etc/alertmanager
